"""Physics Academic Certifications Data"""

from .class_11 import CERTIFICATION as CLASS_11_CERT, QUESTIONS as CLASS_11_QUESTIONS
from .class_12 import CERTIFICATION as CLASS_12_CERT, QUESTIONS as CLASS_12_QUESTIONS
from .bachelor_year_1 import CERTIFICATION as BACHELOR_1_CERT, QUESTIONS as BACHELOR_1_QUESTIONS
from .bachelor_year_2 import CERTIFICATION as BACHELOR_2_CERT, QUESTIONS as BACHELOR_2_QUESTIONS
from .bachelor_year_3 import CERTIFICATION as BACHELOR_3_CERT, QUESTIONS as BACHELOR_3_QUESTIONS

CERTIFICATIONS = [
    CLASS_11_CERT,
    CLASS_12_CERT,
    BACHELOR_1_CERT,
    BACHELOR_2_CERT,
    BACHELOR_3_CERT
]