"""Science Academic Certifications Data"""

from .class_1 import CERTIFICATION as CLASS_1_CERT, QUESTIONS as CLASS_1_QUESTIONS
from .class_2 import CERTIFICATION as CLASS_2_CERT, QUESTIONS as CLASS_2_QUESTIONS
from .class_3 import CERTIFICATION as CLASS_3_CERT, QUESTIONS as CLASS_3_QUESTIONS
from .class_6 import CERTIFICATION as CLASS_6_CERT, QUESTIONS as CLASS_6_QUESTIONS
from .class_7 import CERTIFICATION as CLASS_7_CERT, QUESTIONS as CLASS_7_QUESTIONS
from .class_8 import CERTIFICATION as CLASS_8_CERT, QUESTIONS as CLASS_8_QUESTIONS
from .class_9 import CERTIFICATION as CLASS_9_CERT, QUESTIONS as CLASS_9_QUESTIONS
from .class_10 import CERTIFICATION as CLASS_10_CERT, QUESTIONS as CLASS_10_QUESTIONS

CERTIFICATIONS = [
    CLASS_1_CERT,
    CLASS_2_CERT, 
    CLASS_3_CERT,
    CLASS_6_CERT,
    CLASS_7_CERT,
    CLASS_8_CERT,
    CLASS_9_CERT,
    CLASS_10_CERT
]